### ISSUE TITLE
Email template enhancements

### ISSUE THREAD

**Issue by goldpbear** [mapseed/api#117]
Thanks to @zmbc we have a place email template feature on the API that allows us to automatically send emails when new content is created on a Mapseed map.

This works great, but a recent use case suggested some useful enhancements:

- [x] Send email on comment submissions -- #124 
- [x] The option to list multiple emails in the BCC field -- #121
- [x] Send email to the BCC list even if the no submitter email is provided -- #122
