### ISSUE TITLE
Django 1.8 DRF 3.x upgrade

### ISSUE THREAD

**Issue by modulitos** [mapseed/api#131]
These are the tasks we will need to complete before we can deploy the Django/DRF upgrade:

 - [x] Ensure that all unit tests are passing (thanks Zeb!)
 - [ ] Fix CircleCI tests by updating CircleCI config with a new Docker container
 - [ ] Merge `master` branch into our `django1.8-drf3-upgrades` feature branch. This includes handling any migration conflicts as well.
 - [ ] Deploy on our staging api and conduct user acceptance testing
   - [ ] use a replica set of or prod data for the staging api
   - [ ] Migrate the existing data
